# **Name : Abhishek Subhash Swami**
# **Roll No. 13**

# **Experiment 1 : Implementation of array operations using Numpy**

## Import required packages

In [2]:
import numpy as np

## Creating an 1D Array

In [3]:
arr1D=np.array([1,2,3,4,5,6])
print(arr1D)

[1 2 3 4 5 6]


## Creating 2D Array



In [4]:
arr2D=np.array([[1,2,3],[4,5,6]])
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

## Creating 3D Array

In [5]:
arr3D= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Accessing elements of 1D, 2D and 3D array




In [6]:
#1D array
for i in range(len(arr1D)):
  print(arr1D[i])

1
2
3
4
5
6


In [7]:
#2D array
'''for accessing elements from 2D array, we need to specify row and column
inside [row][column] respectively.'''

for i in range(0,2):            #since we have 2 rows in arr2D
  for j in range(0,3):          #since we have 3 columns in arr2D
    print(arr2D[i][j],end=' ')
  print("\n")


1 2 3 

4 5 6 



In [8]:
#3D array
'''for accessing elements from 3D array, we need 3 parameters,
plane, row and column. 
syntax:
        array_name[plane][row][column]'''

for i in range(0,2): 
  print(f'Plane {i}\n')           #since we have 2 planes in arr3D
  for j in range(0,2):            #since we have 2 rows in arr3D in each plane
    for k in range(0,3):          #since we have 3 columns in arr3D in each plane
      print(arr3D[i][j][k],end=' ')
    print('\n')
  print('\n')

Plane 0

1 2 3 

4 5 6 



Plane 1

7 8 9 

10 11 12 





## Changing elements of 1D, 2D and 3D array

In [9]:
#1D array

array1D=np.array([12,22,32,42,52,62])

#changing 4th element of array1D i.e. 42 with 92
array1D[3]=92

#show changes
print(array1D)

[12 22 32 92 52 62]


In [10]:
#2D array

array2D=np.array([[12,22,32],
                 [42,52,62]])

#changing element from 2nd row and 2nd column i.e. 52 with 92
array2D[1][1]=92

#show changes
print(array2D)

[[12 22 32]
 [42 92 62]]


In [11]:
#3D array

array3D=np.array([[[10,20,30],
                   [40,50,60]],
                  [[70,80,90],
                  [100,110,120]]])

#changing element from 1st plane, 2nd row and 2nd column i.e. 50 with 45 
array3D[0][1][1]=45

#show changes
print(array3D)

[[[ 10  20  30]
  [ 40  45  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [12]:
#replace all occurances

arr=np.arange(1,50,dtype=int)
arr=arr.reshape(7,7)
print('Before : \n',arr)

#replace all occurances of numbers divisible by 7 with 0
arr[arr%7==0]=0
#we are using boolean expression to replace values
print('After : \n',arr)

Before : 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]
After : 
 [[ 1  2  3  4  5  6  0]
 [ 8  9 10 11 12 13  0]
 [15 16 17 18 19 20  0]
 [22 23 24 25 26 27  0]
 [29 30 31 32 33 34  0]
 [36 37 38 39 40 41  0]
 [43 44 45 46 47 48  0]]


## NumPy Array Operations

In [13]:
# numpy arange() function is used to create array with evenly spaced values
# np.arange(start,stop,step,dtype)

#create array of values from 10 to 50 with step value of 3
arr1=np.arange(10,50,3,dtype=int)
print(arr1)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [14]:
# numpy zeros() function is used to create array with all zeroes
# np.zeros(shape, dtype, order)

arr2=np.zeros((3,3),dtype=int, order='C')     #order 'C' refers to row-major i.e. C style memory allocation
print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
# numpy ones() function is used to create array with all ones
# np.ones(shape, dtype, order)

arr3=np.ones((3,3),dtype=int,order='F')     #order 'F' refers to column-major i.e. Fortran style memory allocation
print(arr3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
# numpy identity() function is used to create 2D array of 'n' size with diagonal 1 and 0 elsewhere i.e. identity matrix
# np.identity(size,dtype)

arr4=np.identity(4,dtype=int)
print(arr4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [17]:
# numpy eye() function is used to create 2D array with diagonal 1 and 0 elsewhere similar to identity()
# but here we can give each dimension separately.
# np.eye(row, column, diagonal-start, dtype, order)

arr5=np.eye(4,5,1,dtype=int,order='C')
print(arr5)


[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [18]:
# numpy empty() function is used to create an uninitialized array of specified shape and data type
# np.empty(shape,dtype,order)

arr6=np.empty((3,3),dtype=int)
print(arr6)

[[           48241936                   0          4294967295]
 [7146761174949785447 7451595009854631788 8391101629866538353]
 [3564087168171340399 8606188051543507246                 115]]


In [19]:
# numpy full() function is used to create a new array of a specified shape and type, and fills it with a specified value.
# np.full(shape, fill_value, dtype=None, order='C', *, like=None)

arr7=np.full((2,2),3,dtype=int)
print(arr7)

[[3 3]
 [3 3]]


In [20]:
arr8=np.full_like(arr7,9)
arr8

array([[9, 9],
       [9, 9]])

## ndim()

In [25]:
# ndim is a function in the NumPy library that returns the number of dimensions of a given NumPy array
# np.ndim(array)

arr9=np.array([[12,23,34,45],[76,56,45,43]])
print(arr9)
print(f"\nNo. of dimensions : {np.ndim(arr9)}")


[[12 23 34 45]
 [76 56 45 43]]

No. of dimensions : 2


## append()

In [33]:
# append() is a function in the NumPy that appends values to the end of an array

# Create a 1-dimensional array
arr10 = np.array([1, 2, 3])
print(arr10)

[1 2 3]


In [34]:
# Append a single value to the end of the array
arr10 = np.append(arr10, 4)
print(arr10)

[1 2 3 4]


In [35]:
# Append multiple values to the end of the array
arr10 = np.append(arr10, [5, 6, 7])
print(arr10)

[1 2 3 4 5 6 7]


In [36]:
# Create a 2-dimensional array
arr11 = np.array([[1, 2], [3, 4]])
print(arr11)

[[1 2]
 [3 4]]


In [37]:
# Append a row to the end of the array
arr11= np.append(arr11, [[5, 6]], axis=0)
print(arr11)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
# Append a column to the end of the array
arr11 = np.append(arr11, [[7], [8], [9]], axis=1)
print(arr11)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


## concatenate()

In [39]:
# concatenate() is a function in the NumPy that concatenates (joins) two or more arrays along a specified axis.

# Create two 1-dimensional arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate the arrays along the 0th axis (i.e., vertically)
c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6]


In [40]:
# Create two 2-dimensional arrays
d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6], [7, 8]])

# Concatenate the arrays along the 0th axis (i.e., vertically)
f = np.concatenate((d, e), axis=0)
print(f)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
# Concatenate the arrays along the 1st axis (i.e., horizontally)
g = np.concatenate((d, e), axis=1)
print(g)

[[1 2 5 6]
 [3 4 7 8]]
